### ISSUE TITLE
Use of NUmber.isNaN function from ES6: issue for IE and Safari

### ISSUE THREAD

**Issue by bwittwer** [BorisKozo/angular-async-locks#3]
Hello!

We would like to use your cool library in an app that should support the most common browsers. However you are using some functions that are part of the ES6 draft spec like the **Number.isNan()** function (http://people.mozilla.org/~jorendorff/es6-draft.html#sec-number.isnan).

This could be an issue as it is not yet supported by IE and Safari (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN#Browser_compatibility).

Do you pruposely used such new methods? Would it be possible to have a stable version not relying on such new features?

Thanks,
Kind Regards,
Bernard.

**Comment by BorisKozo** [comment]
Hi,

Thank you for finding this issue.
I must have confused Number.isNaN() with the regular isNaN().

I will fix it today.

Thanks again,
Boris.

**Comment by BorisKozo** [comment]
I fixed it. I hope its OK now.

**Comment by bwittwer** [comment]
Hi Boris,

Thanks a lot for the quick fix.
I will let you know if I find any other issues.

Cheers,
Bernard.
