### ISSUE TITLE
add a version tag please

### ISSUE THREAD

**Issue by martinmuellerrohde** [BorisKozo/angular-async-locks#5]
Hi,
could you please add a version tag, to make sure if I download your great package with bower I'll get a well defined version?
Best regards,
martin

**Comment by BorisKozo** [comment]
Done.
Please tell me if this is enough to close the issue.
Thanks

**Comment by martinmuellerrohde** [comment]
Super!

I ran
   _bower register angular-async-locks
git://github.com/BorisKozo/angular-async-locks.git
http://github.com/BorisKozo/angular-async-locks.git_
to register your package (see
http://bower.io/docs/creating-packages/#register )
and now I can specify in my bower.json simply

...
"dependencies": {
  "angular": "~1.3.17",
  _..._

  "angular-async-locks": "~0.3.1",

...

to retrieve version 0.3.1.

Yes, you can close the issue.

Many thanks a lot Boris!

Regards,
Martin

2015-07-08 19:46 GMT+02:00 Boris Kozorovitzky notifications@github.com:

**Comment by BorisKozo** [comment]
Cool! Thanks.
